POST http://localhost:3000/register
Content-Type: application/json

{
"username": "adam_richardku",
"name": "Adam Richard",
"password": "richard123",
"gender": "male",
"location": "Detroit"
}

###
POST http://localhost:3000/login/
Content-Type: application/json 

{
"username": "adam_richardku",
"password": "richard123"
}

###
PUT http://localhost:3000/change-password
Content-Type: application/json

{
"username": "adam_richardku",
"oldPassword": "richard_567",
"newPassword": "rich"
}
